---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ci-cd-pipeline-run-
spec:
  pipelineRef:
    name: ci-cd-pipeline-simple
  params:
    - name: repo-url
      value: "https://github.com/prodevku888/ci-cd-final-project.git"
    - name: branch
      value: "master"
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: oc-lab-pvc
