---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  params:
    - name: repo-url
      description: The git repository URL
      type: string
      default: "https://github.com/r4diorusak/ci-cd-final-project.git"
    - name: branch
      description: The git branch to clone
      type: string
      default: "master"
    - name: app-name
      description: The name of the application
      type: string
      default: "cicd-app"
    - name: build-image
      description: The built image name
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/default/cicd-app:latest"
  workspaces:
    - name: output
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output
    
    - name: git-clone
      taskRef:
        name: git-clone
      runAfter:
        - cleanup
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      workspaces:
        - name: output
          workspace: output
    
    - name: flake8
      taskRef:
        name: flake8
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: output
    
    - name: nose
      taskRef:
        name: nose
      runAfter:
        - flake8
      params:
        - name: args
          value: "-v --with-spec --spec-color"
      workspaces:
        - name: source
          workspace: output
    
    - name: buildah
      taskRef:
        name: buildah
      runAfter:
        - nose
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output
    
    - name: deploy
      taskRef:
        name: openshift-client
      runAfter:
        - buildah
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
